spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: root
    password: TAN@321cot
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

